config/routes.rb
Rails.application.routes.draw do

  root to: "jobs#premium"

  get '/login', to: 'login#login'
  get '/logout', to: 'login#destroy'
  post '/authenticate', to: 'login#authenticate'

  resources :companies, only: [:new, :create, :index]

  resources :cars

  resources :jobs do
    get '/comments', to: 'jobs#comments'
    post '/comments', to: 'comments#create'
  end

  delete '/comments/:id', to: 'comments#destroy', as: :comment

  get '/hello/world'

end

app/models/car.rb
class Car < ActiveRecord::Base
  attr_accessor :brand, :model, :year
  validates_presence_of :brand, :model
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :job, counter_cache: true
  validates_presence_of :name, :body, :job_id
end

app/models/company.rb
require 'bcrypt'

class Company < ActiveRecord::Base
  has_many :jobs

  validates_presence_of :email, :name, :password
  validates_uniqueness_of :email
  validates_length_of :password, minimum: 6
  validates_confirmation_of :password

  def password=(password)
    @password = password
    self.encrypted_password = BCrypt::Password.create(@password)
  end

  def password
    @password
  end

  def valid_password?(password)
    BCrypt::Password.new(encrypted_password) == password
  end
end

app/models/job.rb
class Job < ActiveRecord::Base
  belongs_to :company
  has_many :comments

  scope :most_recent, -> { order('created_at DESC') }
  validates_presence_of :description, :title, :company_id
  
  def to_param
    "#{id}-#{title}"
  end

  def self.find_by_slug(slug)
    job = find(slug)
    
    if (job.to_param == slug)
      job
    else
      raise SlugNotFoundError.new(job)
    end
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :set_locale
  
  rescue_from SlugNotFoundError, :with => :redirect_to_right_slug

  private
  def redirect_to_right_slug(error)
    puts error.slug
    redirect_to error.slug
  end
  
  def current_company
    @current_company ||= if session[:company_id]
      Company.find_by_id(session[:company_id])
    end
  end

  def set_locale
    locale = params[:locale] || cookies[:locale]
    if locale.present?
      I18n.locale = locale
      cookies[:locale] = { value: locale, expires: 30.days.from_now}
    end
  end

  helper_method :current_company
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @job = Job.find(params[:job_id])
    @comment = @job.comments.build(comment_params)
    
    if success = @comment.save
      CompanyMailer.new_comment(@job, @comment).deliver
    end
    
    if success
      flash[:notice] = "Comment was create successfully!"
    else
      flash[:alert] = "Please fill all the fields!"
    end
    redirect_to @job
  end


  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to @comment.job, notice: 'Comment destroyed successfully!'
  end

  private
  def comment_params
      params.require(:comment).permit(:name, :body)
  end

end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController

  def index
    @companies = Company.all
  end

  def new
    @company = Company.new
  end

  def create
    @company = Company.new(company_params)

    if @company.save
      redirect_to root_path, notice: 'Company saved successfully!'
    else
      render action: 'new'
    end
  end

  private
  def company_params
    params.require(:company).permit(:name, :email, :password, :password_confirmation)
  end

end

app/controllers/hello_controller.rb
class HelloController < ApplicationController
  def world
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController

  before_filter :authorize_company, only: [:new, :create, :edit, :update, :destroy]
  before_action :set_job, only: [:edit, :update, :destroy], except: [:show]

  # GET /jobs
  # GET /jobs.json
  def index
    @jobs = Job.most_recent.includes(:company).all
  end

  def premium
    @jobs = Job.where(premium: true).most_recent.includes(:company).paginate(page: params[:page], per_page: 10)
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
    @job = Job.find_by_slug(params[:id])
  end

  # GET /jobs/new
  def new
    @job = current_company.jobs.build
  end

  # GET /jobs/1/edit
  def edit
  end

  def comments
    @comments = Comment.where(job_id: params[:job_id])
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = current_company.jobs.build(job_params)

    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: 'Job was successfully created.' }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url, notice: 'Job was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_job
    @job = current_company.jobs.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def job_params
    params.require(:job).permit(:title, :description, :premium)
  end

  def authorize_company
    unless current_company
      redirect_to root_path, alert: "You need to login to continue."
    end
  end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController

  def login
  end

  def authenticate
    company = Company.find_by_email(params[:company][:email])

    if company && company.valid_password?(params[:company][:password])
      session[:company_id] = company.id
      redirect_to root_path
    else
      flash.now[:alert] = 'Invalid e-mail or password'
      render 'login'
    end
  end

  def destroy
    session.clear
    redirect_to root_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
  def job_title(job)
    title = raw(" #{h(job.title)} - #{h(job.company.name)}")

    title = content_tag(:i, ' ', class: 'glyphicon glyphicon-star') + title if job.premium
    
    title
  end
end

app/views/comments/_comment.html.erb
<div class="comment_item">
	<div class="comment_header">
		<%= comment.name %> said:
	</div>
	<div class="comment_body">
		<%= comment.body %>
	</div>
	<div class="input-group">
		<div class="input-group-addon"><%= t('.sent') %> <b><%= time_ago_in_words comment.created_at %></b> <%= t('.ago') %></div>
		<% if current_company == @job.company %>
			<%= button_to comment_path(comment), method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn btn-danger btn-radius-right' do %>
				<i class="glyphicon glyphicon-trash"></i>
			<% end %>
		<% else %>
			<%= link_to root_path, class: 'btn btn-default btn-radius-right', disabled: 'disabled' do %>
				<i class="glyphicon glyphicon-time"></i>
			<% end %>
		<% end %>
	</div>
</div>

app/views/comments/_form.html.erb
<%= form_for [@job, Comment.new] do |f| %>
	<div class="field">
		<p>
			<%= f.label :name %>
		</p>
		<p>
			<%= f.text_field :name, class: 'form-control' %>
		</p>
	</div>

	<div class="field">
		<p>
			<%= f.label :body %>
		</p>
		<p>
			<%= f.text_area :body, class: 'form-control' %>
		</p>
	</div>

	<div class="actions">
		<%= button_tag(type: 'submit', class: "btn btn-primary btn-full") do %>
		 	<i class="glyphicon glyphicon-send"></i> <%= t('.send') %>
		<% end %>
	</div>
<% end %>

app/views/companies/_company.html.erb
<tr>
	<td>
		<%= company.name %>
	</td>
	<td>
		<%= company.email %>
	</td>
	<td>
		<a href="#">Edit</a>
	</td>
	<td>
		<a href="#">Delete</a>
	</td>
</tr>

app/views/companies/_form.html.erb
<%= form_for(@company, html: { class: 'form-horizontal' }) do |f| %>
  <% if @company.errors.any? %>
	<% @company.errors.full_messages.each do |msg| %>
    	<div class="alert alert-warning">
        	<button type="button" class="close" data-dismiss="alert" aria-label="Close">
				<span aria-hidden="true">&times;</span>
			</button>
			<%= msg %>
        </div>
  	<% end %>
  <% end %>

  <div class="control-group">
    <%= f.label :name, class: 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, class: 'form-control' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :email, class: 'control-label' %>
    <div class="controls">
      <%= f.text_field :email, class: 'form-control' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :password, class: 'control-label' %>
    <div class="controls">
      <%= f.password_field :password, class: 'form-control' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :password_confirmation, class: 'control-label' %>
    <div class="controls">
      <%= f.password_field :password_confirmation, class: 'form-control' %>
    </div>
  </div>
  <div class="actions">
    <%= link_to jobs_path, class: 'btn btn-default' do %>
    	<i class="glyphicon glyphicon-remove"></i> <%= t('.cancel')%>
    <% end %>
    <%= button_tag(type: 'submit', class: 'btn btn-primary') do %>
    	<i class="glyphicon glyphicon-ok"></i> <%= t('.send')%>
    <% end %>
  </div>
<% end %>

app/views/companies/index.html.erb
<h1>Companies</h1>

<table>
	<thead>
		<tr>
			<td>Name</td>
			<td>Email</td>
			<td>Edit</td>
			<td>Delete</td>
		</tr>
	</thead>
	<tbody>
		<%= render @companies %>
	</tbody>
</table>

app/views/companies/new.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    New Company
  </div>
  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>

app/views/hello/world.html.erb
<h1>Hello World</h1>
<p> <%= Time.now %> </p>

app/views/jobs/_form.html.erb
<%= form_for(@job) do |f| %>
  <% if @job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
      <% @job.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="field">
  	<%= f.label :premium %><br/>
  	<%= f.check_box :premium %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description, class: 'form-control ckeditor' %>
  </div>
  <div class="actions">
    <%= link_to jobs_path, class: 'btn btn-default' do %>
    	<i class="glyphicon glyphicon-remove"></i> <%= t('.cancel')%>
    <% end %>
    <%= button_tag(type: 'submit', class: 'btn btn-primary') do %>
    	<i class="glyphicon glyphicon-ok"></i> <%= t('.send')%>
    <% end %>
  </div>
<% end %>

app/views/jobs/_job.html.erb
<div class="panel panel-default">
	<div class="panel-heading">
			<%= job_title job %>
	</div>
	<div class="panel-body">
		<%= simple_format job.description %>
			<div class="input-group">
				<div class="input-group-addon">
					<i class="glyphicon glyphicon-comment"></i> <%= pluralize job.comments.size, t('.comment') %>
				</div>
				<% if current_company == job.company %>
					<%= link_to edit_job_path(job), class: 'btn btn-warning btn-no-radius btn-edit-job' do %>
						<i class="glyphicon glyphicon-pencil"></i> 
					<% end %>
					<%= button_to job, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-no-radius btn-delete-job' do %>
						<i class="glyphicon glyphicon-trash"></i> 
					<% end %>
				<% end %>
				<%= link_to job,  class: 'btn btn-info btn-radius-right' do %>
					<i class="glyphicon glyphicon-zoom-in"></i> 
				<% end %>
			</div>
	</div>
</div>

app/views/jobs/edit.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    <%= t('.header')%>
  </div>
  <div class="panel-body">
		<%= render 'form' %>
  </div>
</div>

app/views/jobs/index.html.erb
<h1><%= t('.header')%></h1>

<%= render @jobs %>

app/views/jobs/new.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    <%= t('.header')%>
  </div>
  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>

app/views/jobs/premium.html.erb
<h1><%= t('.header') %></h1>

<div id="jobs">
  <%= render @jobs %>
</div>
<%= will_paginate @jobs%>

app/views/jobs/show.html.erb
<div class="row">
	<div class="col-sm-8">
		<div class="panel panel-default">
			<div class="panel-heading">
				<%= job_title @job %>
			</div>
			<div class="panel-body">
				<%= simple_format @job.description %>
			</div>
			<div class="panel-footer">
				<div class="input-group">
					<div class="input-group-addon">
						<i class="glyphicon glyphicon-comment"></i>
						<%= pluralize @job.comments.size, t('.comment') %>
					</div>
					<% if current_company == @job.company %>
						<%= link_to edit_job_path(@job), class: 'btn btn-warning btn-radius-right' do %>
							<i class="glyphicon glyphicon-pencil"></i>
						<% end %>
					<% else %>
						<%= link_to t('root.back'), jobs_path, class: 'btn btn-default btn-radius-right' %>
					<% end%>
				</div>
			</div>
		</div>
	</div>


	<div class="col-sm-4">
		<div class="panel panel-primary">
			<div class="panel-heading">
				<%= t('.commentform')%>
			</div>
			<div class="panel-body">
				<%= render "comments/form" %>
			</div>
		</div>
	</div>
</div>



<div class="panel panel-default">
	<div class="panel-heading">
		<%= t('.comments')%>
	</div>
	<div class="panel-body">
		<%= render @job.comments %>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>JobBoard</title>
		<%= stylesheet_link_tag    'application', media: 'all' %>
		<%= csrf_meta_tags %>
	</head>
	<body>
		<header class="navbar navbar-inverse navbar-static-top bs-docs-nav" id="top" role="banner">
			<div class="container">
				<div class="navbar-header">
					<button class="navbar-toggle collapsed" type="button" data-toggle="collapse" data-target=".bs-navbar-collapse">
						<span class="sr-only">Toggle navigation</span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
					<a href="../" class="navbar-brand"><%= t("menu.job_board") %></a>
				</div>
				<nav class="collapse navbar-collapse bs-navbar-collapse">
					<ul class="nav navbar-nav">
						<li>
							<%= link_to t("menu.premium_jobs"), root_path %>
						</li>
						<li>
							<%= link_to t("menu.all_jobs"), jobs_path %>
						</li>
						<% if current_company %>
							<li>
								<%= link_to t("menu.new_job"), new_job_path %>
							</li>
							<li>
								<%= link_to t("menu.new_company"), new_company_path %>
							</li>
						<% end %>
					</ul>
					<ul class="nav navbar-nav navbar-right">
						<% if current_company %>
							<li>
								<a href="#"><%= t("menu.logged.as", username: current_company.name) %></a>
							</li>
							<li>
								<%= link_to t("menu.logout"), logout_path %>
							</li>
							<% else %>
							<li>
								<%= link_to t("menu.login"), login_path, id: 'btn-login-menu' %>
							</li>
						<% end %>
					</ul>
					<ul class="nav navbar-nav navbar-right">
					  	<li>
					  		<a id="btn-to-english" href="?locale=en">
					  			<img src="/static/img/usa-flag.png" style="height: 20px;"/>
					  		</a>
					  	</li>
					  	<li>
					  		<a id="btn-to-portuguese" href="?locale=pt-BR">
					  			<img src="/static/img/br-flag.png" style="height: 20px;"/>
					  		</a>
					  	</li>
					</ul>
				</nav>
			</div>
		</header>

		<div class="container">
			<% if notice %>
				<p id="notice" class="alert alert-info">
					<button type="button" class="close" data-dismiss="alert" aria-label="Close">
					  <span aria-hidden="true">&times;</span>
					</button>
					<%= notice %>
				</p>
			<% end %>
			<% if alert %>
				<p id="alert" class="alert alert-warning">
					<button type="button" class="close" data-dismiss="alert" aria-label="Close">
					  <span aria-hidden="true">&times;</span>
					</button>
					<%= alert %>
				</p>
			<% end %>
			<%= yield %>
		</div>

		<%= javascript_include_tag 'application' %>
		<script src="/static/bootstrap-switch.js"></script>
		<script>
			$(document).ready(function(){
				$("input[type=checkbox]").bootstrapSwitch();
			});
		</script>
	</body>
</html>

app/views/login/_form.html.erb
<%= form_for(Company.new, url: authenticate_path, html: { class: 'form-horizontal' }) do |f| %>
    <div class="control-group">
      <%= f.label :email, class: 'control-label' %>
      <div class="controls">
        <%= f.text_field :email, class: 'form-control'%>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :password, class: 'control-label' %>
      <div class="controls">
        <%= f.password_field :password, class: 'form-control' %>
      </div>
    </div>
    <div class="control-group controls">
      <%= f.submit "Login", class: 'btn btn-primary', id: 'btn-login' %>
    </div>
<% end %>

app/views/login/login.html.erb
<div id="panel-login" class="panel panel-primary">
  <div class="panel-heading">
      Company - Login
  </div>
  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>